### ISSUE TITLE
Add process user's selection

### ISSUE THREAD

**Issue by malerisch** [silentsignal/burp-piper#16]
hi, first of all, very cool extension!
I would like to ask if it is possible to add the possibility to "process selection" as well so that any input selected by the user with the mouse can be passed to piper, without using filters.
Thanks and great work!

**Comment by dnet** [comment]
Thanks for the compliment!

Could you explain your wish a bit more? Filters are optional, if you don't specify any filter to a tool (or remove them using the `Remove` button in the editor), it will be available to any input. Is your proposal trying to circumvent an existing filter, like a "force" option?

There are two further things that could prevent the user from using a certain tool for some selections:

 - if the tool has specified the minimum and/or maximum amount of inputs it can consume, and the number of selected items is not within that range, or
 - if the command set for the tool doesn't have the `Pass HTTP headers to command` checkbox checked and the selection has no HTTP body (such as `GET` / `HEAD` requests or `201` / otherwise empty responses).

Could you elaborate on what you propose to change in this behavior using the new "possibility"?

**Comment by malerisch** [comment]
Hi,
Thanks for your reply - let me give you an example. So I want to grab either from a HTTP request or response a value (e.g. a base64 encoded value of a Json parameter). I select it with my mouse, then right click against the selected block and then would like piper to only process what I selected through the command of my choice.
Thanks.

**Comment by dnet** [comment]
Thanks for the clarification, I released [v0.6.1](https://github.com/silentsignal/burp-piper/releases/tag/v0.6.1) which includes this feature. If you open the context menu after selecting something in a message editor / viewer, a new menu item appears to process that selection. If it's not exactly as you imagined, feel free to reopen this issue.

**Comment by malerisch** [comment]
hi, I just gave it a try - it works perfectly and as I imagined it! Thanks again, that was very quick.
